### ISSUE TITLE
[DATABASE] - Criar tabelas do banco de dados

### ISSUE THREAD

**Issue by WhiteSummeRK** [WhiteSummeRK/pi_semestre6#1]
Criar tabelas do banco de dados com base na modelagem do lucas borges

**Comment by lucxsborges** [comment]
--
-- Database: 'pi_semestre6'
--

-- --------------------------------------------------------

--
-- Estrutura da tabela 'categorias'
--

CREATE TABLE categorias (
  cod_categoria int(11) NOT NULL AUTO_INCREMENT,
  nome varchar(255) NOT NULL,
  descricao varchar(255) NOT NULL,
  PRIMARY KEY (cod_categoria)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Estrutura da tabela 'conta_hospede'
--

CREATE TABLE conta_hospede (
  cod_conta int(11) NOT NULL AUTO_INCREMENT,
  cod_hospede int(11) NOT NULL,
  abertura date NOT NULL DEFAULT '0000-00-00',
  fechamento date NOT NULL DEFAULT '0000-00-00',
  `status` varchar(255) NOT NULL,
  valor decimal(10,0) NOT NULL,
  PRIMARY KEY (cod_conta)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Estrutura da tabela 'funcionario'
--

CREATE TABLE funcionario (
  cod_funcionario int(11) NOT NULL AUTO_INCREMENT,
  cod_usuario int(11) NOT NULL,
  nome varchar(255) NOT NULL,
  cpf varchar(11) NOT NULL,
  cargo varchar(255) NOT NULL,
  setor varchar(255) NOT NULL,
  PRIMARY KEY (cod_funcionario)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Estrutura da tabela 'hospedagem'
--

CREATE TABLE hospedagem (
  cod_hospedagem int(11) NOT NULL AUTO_INCREMENT,
  cod_quarto int(11) NOT NULL,
  cod_hospede int(11) NOT NULL,
  data_entrada date NOT NULL DEFAULT '0000-00-00',
  data_saida date NOT NULL DEFAULT '0000-00-00',
  obs varchar(255) NOT NULL,
  valor_despesas decimal(10,0) NOT NULL,
  PRIMARY KEY (cod_hospedagem)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Estrutura da tabela 'hospede'
--

CREATE TABLE hospede (
  cod_hospede int(11) NOT NULL AUTO_INCREMENT,
  cod_usuario int(11) NOT NULL,
  nome varchar(255) NOT NULL,
  cpf varchar(11) NOT NULL,
  telefone varchar(11) NOT NULL,
  PRIMARY KEY (cod_hospede)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Estrutura da tabela 'item_pedido'
--

CREATE TABLE item_pedido (
  cod_item int(11) NOT NULL AUTO_INCREMENT,
  cod_servico int(11) NOT NULL,
  cod_funcionario int(11) NOT NULL,
  qtd int(11) NOT NULL,
  valor decimal(10,0) NOT NULL,
  `status` varchar(255) NOT NULL,
  PRIMARY KEY (cod_item)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Estrutura da tabela 'pedido'
--

CREATE TABLE pedido (
  cod_pedido int(11) NOT NULL AUTO_INCREMENT,
  cod_hospede int(11) NOT NULL,
  cod_quarto int(11) NOT NULL,
  `data` date NOT NULL DEFAULT '0000-00-00',
  `status` varchar(255) NOT NULL,
  valor_total decimal(10,0) NOT NULL,
  PRIMARY KEY (cod_pedido)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Estrutura da tabela 'quarto'
--

CREATE TABLE quarto (
  cod_quarto int(11) NOT NULL AUTO_INCREMENT,
  numero int(11) NOT NULL,
  andar int(11) NOT NULL,
  descricao varchar(255) NOT NULL,
  valor_diaria decimal(10,0) NOT NULL,
  `status` varchar(15) NOT NULL DEFAULT 'livre',
  PRIMARY KEY (cod_quarto)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Estrutura da tabela 'servico'
--

CREATE TABLE servico (
  cod_servico int(11) NOT NULL AUTO_INCREMENT,
  cod_categoria int(11) NOT NULL,
  cod_funcionario int(11) NOT NULL,
  nome varchar(255) NOT NULL,
  descricao varchar(255) NOT NULL,
  valor decimal(10,0) NOT NULL,
  PRIMARY KEY (cod_servico)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Estrutura da tabela 'usuarios'
--

CREATE TABLE usuarios (
  cod_usuario int(11) NOT NULL AUTO_INCREMENT,
  usuario varchar(255) NOT NULL,
  senha varchar(255) NOT NULL,
  nome varchar(255) NOT NULL,
  permissao varchar(255) NOT NULL,
  ativo tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (cod_usuario)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;
